package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * @author AIERXUAN
 * @TableName CT_PIG_SHENGCHANWEEKHAO
 */
@Table(name="CT_PIG_SHENGCHANWEEKHAO")
@TableName("CT_PIG_SHENGCHANWEEKHAO")
@Entity
@DynamicInsert
@DynamicUpdate
@Data
@ApiModel(value = "生产周号")
public class CtPigShengchanweekhao implements Serializable {
    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Id
    @TableId
    @GeneratedValue(generator = "JDBC")
    @Column(name = "FID")
    private String fid;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FNUMBER")
    private String fnumber;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FSIMPLENAME")
    private String fsimplename;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FCREATORID")
    private String fcreatorid;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FCREATETIME")
    private Date fcreatetime;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FLASTUPDATEUSERID")
    private String flastupdateuserid;

    /**
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FLASTUPDATETIME")
    private Date flastupdatetime;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FCONTROLUNITID")
    private String fcontrolunitid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "CFWEEKHAO")
    private String cfweekhao;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "CFSTARTDATE")
    private Date cfstartdate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "CFENDDATE")
    private Date cfenddate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "CFYEAR")
    private String cfyear;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "CFMONTH")
    private String cfmonth;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FNAME_L1")
    private String fnameL1;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FNAME_L2")
    private String fnameL2;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FNAME_L3")
    private String fnameL3;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FDESCRIPTION_L1")
    private String fdescriptionL1;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FDESCRIPTION_L2")
    private String fdescriptionL2;

    /**
     * 
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    @Column(name = "FDESCRIPTION_L3")
    private String fdescriptionL3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CT_PIG_SHENGCHANWEEKHAO
     *
     * @mbg.generated Tue Jan 12 14:04:17 CST 2021
     */
    private static final long serialVersionUID = 1L;
}