package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * @author AIERXUAN
 * @TableName CT_PIG_STORAGESRE
 */
@Table(name="CT_PIG_STORAGESRE")
@TableName("CT_PIG_STORAGESRE")
@Data
@Entity
@DynamicInsert
@DynamicUpdate
@ApiModel("库存盘点中的分录")
public class CtPigStoragesre implements Serializable {
    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    @Column(name = "FID")
    private String fid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "FSEQ")
    private Long fseq;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "FPARENTID")
    private String fparentid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFSEMENNUMBERID")
    private String cfsemennumberid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFVARIETYID")
    private String cfvarietyid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFEARNUMBERID")
    private String cfearnumberid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFDOSEID")
    private String cfdoseid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFPEIJINGPERSONID")
    private String cfpeijingpersonid;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFCONFIGURATIONDATE")
    private Date cfconfigurationdate;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFENDDATE")
    private Date cfenddate;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFBATCHNUMBER")
    private String cfbatchnumber;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFBIMUDF0001")
    private Long cfbimudf0001;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFTHEORICALNUMBER")
    private Long cftheoricalnumber;

    /**
     * 
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    @Column(name = "CFFACTNUMBER")
    private Long cffactnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CT_PIG_STORAGESRE
     *
     * @mbg.generated Wed Jan 20 09:23:15 CST 2021
     */
    private static final long serialVersionUID = 1L;
}