package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * @TableName CT_PIG_STORAGESTOCKINGRECORD
 */
@Table(name="CT_PIG_STORAGESTOCKINGRECORD")
@TableName("CT_PIG_STORAGESTOCKINGRECORD")
@Data
@Entity
@DynamicInsert
@DynamicUpdate
@ApiModel("库存盘点")
public class CtPigStoragestockingrecord implements Serializable {
    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    @Column(name = "FID")
    private String fid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FCREATORID")
    private String fcreatorid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FCREATETIME")
    private Date fcreatetime;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FLASTUPDATEUSERID")
    private String flastupdateuserid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FLASTUPDATETIME")
    private Date flastupdatetime;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FCONTROLUNITID")
    private String fcontrolunitid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FNUMBER")
    private String fnumber;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FBIZDATE")
    private Date fbizdate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FHANDLERID")
    private String fhandlerid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FDESCRIPTION")
    private String fdescription;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FHASEFFECTED")
    private Long fhaseffected;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FAUDITORID")
    private String fauditorid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FSOURCEBILLID")
    private String fsourcebillid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FSOURCEFUNCTION")
    private String fsourcefunction;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "FFIVOUCHERED")
    private Long ffivouchered;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFORGUNITID")
    private String cforgunitid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFBEFORESTOCKDATE")
    private Date cfbeforestockdate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFFACTNUMBER")
    private Long cffactnumber;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFBEFOREDATE")
    private Long cfbeforedate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFIFAUDITING")
    private Long cfifauditing;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFAUDITUSERID")
    private String cfaudituserid;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFAUDITDATE")
    private Date cfauditdate;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFTHEORYNUMBER")
    private Long cftheorynumber;

    /**
     * 
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    @Column(name = "CFWEEKHAO")
    private String cfweekhao;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CT_PIG_STORAGESTOCKINGRECORD
     *
     * @mbg.generated Tue Jan 19 10:52:10 CST 2021
     */
    private static final long serialVersionUID = 1L;
}