package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * @author AIERXUAN
 * @TableName CT_PIG_DEMANDAPPLICATION
 */
@Table(name="CT_PIG_DEMANDAPPLICATION")
@TableName("CT_PIG_DEMANDAPPLICATION")
@Data
@Entity
@DynamicInsert
@DynamicUpdate
@ApiModel(value = "精液需求申请")
public class CtPigDemandapplication implements Serializable {
    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    @Column(name = "FID")
    private String fid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FCREATORID")
    private String fcreatorid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FCREATETIME")
    private Date fcreatetime;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FLASTUPDATEUSERID")
    private String flastupdateuserid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FLASTUPDATETIME")
    private Date flastupdatetime;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FCONTROLUNITID")
    private String fcontrolunitid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FNUMBER")
    private String fnumber;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FBIZDATE")
    private Date fbizdate;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FHANDLERID")
    private String fhandlerid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FDESCRIPTION")
    private String fdescription;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FHASEFFECTED")
    private Long fhaseffected;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FAUDITORID")
    private String fauditorid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FSOURCEBILLID")
    private String fsourcebillid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FSOURCEFUNCTION")
    private String fsourcefunction;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "FFIVOUCHERED")
    private Long ffivouchered;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFORIGINATORID")
    private String cforiginatorid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFORGUNITID")
    private String cforgunitid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFDEMANDFIELDID")
    private String cfdemandfieldid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFDEMANDSTATUSID")
    private String cfdemandstatusid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFIFAUDITING")
    private Long cfifauditing;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFAPPLICATIONSTATU")
    private String cfapplicationstatu;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFCOMPLETIONSTATUS")
    private String cfcompletionstatus;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFNOTE")
    private String cfnote;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFAUDITUSERID")
    private String cfaudituserid;

    /**
     * 
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    @Column(name = "CFAUDITDATE")
    private Date cfauditdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CT_PIG_DEMANDAPPLICATION
     *
     * @mbg.generated Thu Jan 14 09:13:31 CST 2021
     */
    private static final long serialVersionUID = 1L;
}