package entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.*;

import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.annotations.ApiModel;
import lombok.Data;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * @TableName CT_PIG_COLLECTIONRECORD
 */
@Data
@Entity
@DynamicInsert
@DynamicUpdate
@Table(name="CT_PIG_COLLECTIONRECORD")
@TableName("CT_PIG_COLLECTIONRECORD")
@ApiModel(value = "精液采集记录")
public class CtPigCollectionrecord implements Serializable {
    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    @Column(name = "FID")
    private String fid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FCREATORID")
    private String fcreatorid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FCREATETIME")
    private Date fcreatetime;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FLASTUPDATEUSERID")
    private String flastupdateuserid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FLASTUPDATETIME")
    private Date flastupdatetime;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FCONTROLUNITID")
    private String fcontrolunitid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FNUMBER")
    private String fnumber;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FBIZDATE")
    private Date fbizdate;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FHANDLERID")
    private String fhandlerid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FDESCRIPTION")
    private String fdescription;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FHASEFFECTED")
    private Long fhaseffected;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FAUDITORID")
    private String fauditorid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FSOURCEBILLID")
    private String fsourcebillid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FSOURCEFUNCTION")
    private String fsourcefunction;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "FFIVOUCHERED")
    private Long ffivouchered;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFDESIGNNUMBERID")
    private String cfdesignnumberid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFORGUNITID")
    private String cforgunitid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFSHCHANLINEID")
    private String cfshchanlineid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFZHUSHEID")
    private String cfzhusheid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFFIELD")
    private String cffield;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFEARNUMBERID")
    private String cfearnumberid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFGENETICSID")
    private String cfgeneticsid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFCOLLECTORID")
    private String cfcollectorid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFCOLLECTIONTIME")
    private Date cfcollectiontime;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFDAYS")
    private Long cfdays;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFAUDITUSERID")
    private String cfaudituserid;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFIFAUDITING")
    private Long cfifauditing;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFWEEKHAO")
    private String cfweekhao;

    /**
     * 
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    @Column(name = "CFISDETECTED")
    private Long cfisdetected;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CT_PIG_COLLECTIONRECORD
     *
     * @mbg.generated Mon Jan 11 08:29:59 CST 2021
     */
    private static final long serialVersionUID = 1L;
}